---
# yaml-language-server: $schema=https://raw.githubusercontent.com/scilus/nf-neuro/main/modules/meta-schema.json
name: "mouse_preqc"
description: Visualize data before running MouseFlow
keywords:
  - strides
  - shells
  - rgb
tools:
  - "scilpy":
      description: "The Sherbrooke Connectivity Imaging Lab (SCIL) Python dMRI processing toolbox."
      homepage: "https://github.com/scilus/scilpy.git"
  - "MRtrix3":
      description: "Toolbox for image processing, analysis and visualisation of dMRI."
      homepage: "https://mrtrix.readthedocs.io/en/latest/"
  - "FSL":
      description: "FSL Toolbox and Scilpy Toolbox"
      homepage: "https://fsl.fmrib.ox.ac.uk/fsl/fslwiki"
input:
  # Only when we have meta
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. `[ id:'test', single_end:false ]`

  - dwi:
      type: file
      description: DWI Nifti image
      pattern: "*.{nii,nii.gz}"

  - bval:
      type: file
      description: B-values in FSL format [DWI].
      pattern: "*.bval"

  - bvec:
      type: file
      description: B-values in FSL format [DWI].
      pattern: "*.bvec"

output:
  #Only when we have meta
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. `[ id:'test', single_end:false ]`

  - dwi_corrected:
      type: file
      description: Nifti volume - DWI corrected
      pattern: "*__dwi_corrected.nii.gz"

  - bval_corrected:
      type: file
      description: B-values corrected in FSL format
      pattern: "*__bval_eddy"

  - bvec_corrected:
      type: file
      description: B-vectors corrected in FSL format
      pattern: "*__dwi_eddy_corrected.bvec"

  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"

authors:
  - "@arnaudbore"