name: Deploy documentation

on:
  push:
    branches:
      - main
  pull_request_target:
    branches:
      - main
      - dev

jobs:
  build-only:
    if: github.event_name == 'pull_request_target'
    uses: scilus/nf-mouse_flow-documentation/.github/workflows/deploy.yml@main
    with:
      deploy: false
    secrets: inherit

  build-and-deploy:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    uses: scilus/nf-mouse_flow-documentation/.github/workflows/deploy.yml@main
    with:
      deploy: true
    secrets: inherit